### ISSUE TITLE
Doesn't compile on Node 0.12 

### ISSUE THREAD

**Issue by mourner** [stackgl/headless-gl#14]
`npm install` on Node 0.12.0 (latest stable) throws errors like:

```bash
$ npm install

> gl@0.0.5 install /Users/mourner/Projects/headless-gl
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/webgl/src/bindings.o
In file included from ../src/bindings.cc:18:
../src/webgl.h:45:28: error: expected class name
class WebGL : public node::ObjectWrap {
                           ^
../src/webgl.h:68:3: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
  JS_METHOD(New);
  ^~~~~~~~~~~~~~
../src/webgl.h:23:65: note: expanded from macro 'JS_METHOD'
#define JS_METHOD(name) static v8::Handle<v8::Value> name(const v8::Arguments& args)
                                                                ^~~~
/Users/mourner/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/bindings.cc:18:
../src/webgl.h:69:3: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
  JS_METHOD(Destroy);
  ^~~~~~~~~~~~~~~~~~
../src/webgl.h:23:65: note: expanded from macro 'JS_METHOD'
#define JS_METHOD(name) static v8::Handle<v8::Value> name(const v8::Arguments& args)
                                                                ^~~~
/Users/mourner/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/bindings.cc:18:
../src/webgl.h:72:3: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
  JS_METHOD(Uniform1f);
  ^~~~~~~~~~~~~~~~~~~~
../src/webgl.h:23:65: note: expanded from macro 'JS_METHOD'
#define JS_METHOD(name) static v8::Handle<v8::Value> name(const v8::Arguments& args)
                                                                ^~~~
/Users/mourner/.node-gyp/0.12.0/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/bindings.cc:18:
../src/webgl.h:73:3: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
  JS_METHOD(Uniform2f);
  ^~~~~~~~~~~~~~~~~~~~
```

**Comment by bsergean** [comment]
I'm getting this error message as well.

**Comment by mikolalysenko** [comment]
Fixed in gl@2.0.0

**Comment by mourner** [comment]
Yay! :+1:
